services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql-data:/var/lib/postgresql/data
      - ./postgres/init_calendar.sh:/docker-entrypoint-initdb.d/init-calendar.sh
      - ./postgres/init_keycloak.sh:/docker-entrypoint-initdb.d/init_keycloak.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 15s
      timeout: 10s
      retries: 3

  keycloak:
    build: ./keycloak
    container_name: keycloak
    environment:
      KC_HOSTNAME_PORT: 8080
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
      KC_DB_SCHEMA: keycloak_schema
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  calendar-app:
    container_name: calendar-app
    image: calendar-app:latest
    ports:
      - "8081:8080"
    depends_on:
      keycloak:
        condition: service_started
      postgres:
        condition: service_healthy
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/calendar_db?currentSchema=calendar_schema
      - DB_USER=calendar_user
      - DB_PASSWORD=calendar_password
      - DB_DRIVER=org.postgresql.Driver
      - HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - LIQUIBASE_SCHEMA=calendar_schema
      - OAUTH_ISSUER_URI=http://keycloak:8080/realms/calendar
      - OAUTH_JWK_SET_URI=http://keycloak:8080/realms/calendar/protocol/openid-connect/certs

volumes:
  postgresql-data: