#!/bin/bash
set -e

KC_USER=keycloak_user
KC_PASSWORD=keycloak_password
KC_SCHEMA=keycloak_schema
DB_NAME=keycloak

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $KC_USER WITH PASSWORD '$KC_PASSWORD';
  CREATE DATABASE $DB_NAME;
  GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $KC_USER;
EOSQL

PGPASSWORD=$KC_PASSWORD psql -v ON_ERROR_STOP=1 --username "$KC_USER" --dbname "$DB_NAME" <<-EOSQL
  CREATE SCHEMA $KC_SCHEMA;
  GRANT ALL PRIVILEGES ON SCHEMA $KC_SCHEMA TO $KC_USER;
EOSQL