name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    name: sonar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up SonarCloud
        uses: sonarsource/sonarcloud-github-action@v2  # Używamy stabilnej wersji
        with:
          organization: collab-timekit  # Zmienna organizacji w SonarCloud
          token: ${{ secrets.SONAR_TOKEN }}  # Token przekazywany przez sekrety organizacji

      - name: SonarCloud Scan
        run: |
          sonar-scanner \
            -Dsonar.projectKey=collab-timekit
            -Dsonar.organization=collab-timekit
            -Dsonar.sources=.
            -Dsonar.host.url=https://sonarcloud.io