name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job to build and test the docker containers
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker images
        run: |
          docker-compose -f docker-infra/kafka/docker-compose.yml build

      - name: Run Docker containers
        run: |
          docker-compose -f docker-infra/kafka/docker-compose.yml up -d

      - name: Wait for services to be ready
        run: |
          sleep 20

      - name: Run Tests (example command)
        run: |
          # You can replace this with your test command, for example:
          # npm test or mvn test, depending on the technology stack.
          echo "Running tests..."

      - name: Shut down containers
        run: |
          docker-compose -f docker-infra/kafka/docker-compose.yml down

  # Job to run SonarCloud analysis
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        with:
          organization: your-sonarcloud-organization
          token: ${{ secrets.SONAR_TOKEN }}

      - name: SonarCloud Scan
        run: |
          sonar-scanner \
            -Dsonar.projectKey=collab-timekit \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io